site_dir: site
site_url: https://unb-mds.github.io/2024-2-Squad04/
docs_dir: DOCS
site_name: Gestão de Inventário
theme:
  # tema personalizado
  name: material
  features:
  - navigation.tabs

   # Configurações de cores e fontes
  palette:
    primary: brown
    accent: grey

    # Palette toggle for light mode
    scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

    # Palette toggle for dark mode
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
    
nav:
  - Início: index.md
  - Sprints: 
    - "Sprint 0": sprints/sprint-00.md
    - "Sprint 1": sprints/sprint-01.md
    - "Sprint 2": sprints/sprint-02.md
    - "Sprint 3": sprints/sprint-03.md
    - "Sprint 4": sprints/sprint-04.md
    - "Sprint 5": sprints/sprint-05.md
    - "Sprint 6": sprints/sprint-06.md
  - Arquitetura: Architecture.md
  # - Storymap (Roadmap): 
  - Protótipos: Protótipos/prototype.md
  # - Requisitos não funcionais:
  - Storymap e Requisitos: 
    - "Product Backlog": backlog.md
    - "Story Map": storymap.md

# rodapé
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/unb-mds/2024-2-Squad05

